services:
  - type: web
    name: mitron-site1-marketplace
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
